### ISSUE TITLE
Kann keine Einträge importieren

### ISSUE THREAD

**Issue by Mottemania** [mhilbrunner/foundryvtt-dnd5e-lang-de#12]
Salut,

ich gehe mal davon aus, dass du deutsch kannst :)

Mit aktivierten Modulen kann ich keine Monster importieren. Nachdem rechtsklick auf die Monster aus dem Kompendium, die mir korrekt auf deutsch angezeigt werden passiert nichts bei "Akteure". Wenn ich die Module deaktiviere und die englischen "Zombies" importiere erscheinen sie wie gewohnt bei den Akteuren. Ich bin auf der Foundry 11 Stable Build 315, falls das hilft.

Trotzdem schon mal vielen Dank für deine Arbeit. Ich freu mich mega darauf!

**Comment by mhilbrunner** [comment]
Das sollte mit Version [2.5.0](https://github.com/mhilbrunner/foundryvtt-dnd5e-lang-de/releases/tag/2.5.0) behoben sein. Bitte einmal updaten und sonst melden, wenn noch ein Fehler auftritt. Danke!
