### ISSUE TITLE
[Issue] Download Fails and manual installation is not recognized

### ISSUE THREAD

**Issue by SirMotte** [mhilbrunner/foundryvtt-dnd5e-lang-de#2]
I'm unsure if there's an issue on my end, I get the following error message on manual installation using the installer.

![grafik](https://user-images.githubusercontent.com/82598692/206322200-90ce7411-f8ce-4320-ab0f-557b05d400f2.png)

And this error if v 1.7.2 is used and I try to update:
![grafik](https://user-images.githubusercontent.com/82598692/206322540-c1a7f921-1a70-4508-b28d-1ae28b35474b.png)

And if new files are copied into 1.7.2 and thus updated manually I get this error message
![grafik](https://user-images.githubusercontent.com/82598692/206326331-e565924f-8696-46ed-817c-6a3d0fd254df.png)

**Comment by SirMotte** [comment]
![grafik](https://user-images.githubusercontent.com/82598692/206322189-71446148-dfae-4e9b-9874-0485108e31e6.png)

**Comment by mhilbrunner** [comment]
Ouch, definitely not only on your end, this was caused by a misplaced `,` in the manifest for version 1.8.0.
I just released version 1.8.1 which should fix this. Thanks for the report!
