### ISSUE TITLE
Übersetzung passt nicht (Natur - Naturkunde)

### ISSUE THREAD

**Issue by vt-tom** [mhilbrunner/foundryvtt-dnd5e-lang-de#4]
Die Übersetzung von Nature passt nicht zur offizellen Übersetzung.
Es müsste Naturkunde und nicht Natur heißen.

(Ja ich weiß ist ne Kleinigkeit und hat für mich auch super niedrige Prio :) )

**Comment by mhilbrunner** [comment]
@vt-tom Das war eine bewusste Entscheidung.

Die neueren Übersetzungen von WOTC benutz(t)en "Natur" statt "Naturkunde" ([vergleiche](https://www.dnddeutsch.de/falsch/?search=natur)). Gibt es eine neuere Veröffentlichung (post-Übersetzung durch WOTC statt Ulisses), die stattdessen wieder Naturkunde benutzt?

**Comment by vt-tom** [comment]
Oh, ich hab noch die Ulisses Übersetzung
Dann bin ich wohl nicht up to date... Sorry. Issue kann geschlossen werden 😊

**Comment by mhilbrunner** [comment]
Kein Ding, ist ja alles ein wenig unübersichtlich :)

**Comment by mhilbrunner** [comment]
@vt-tom Das Deutsche SRD wurde jetzt offiziell veröffentlicht, und da ist's tatsächlich wieder Naturkunde. Spricht dafür, das zu ändern. Abweichungen:

- Naturkunde (aktuell in Foundry "Natur")
- Überlebenskunst (aktuell in Foundry "Überleben")

Bei Animal Handling bleiben sie bei der neueren Übersetzung "Mit Tieren umgehen" statt der älteren "Tierkunde".

Link (PDF): https://media.wizards.com/2023/downloads/dnd/SRD_CC_v5.1_DE.pdf

**Comment by vt-tom** [comment]
@mhilbrunner ah, das ist ja spannend. Danke für die info.

**Comment by mhilbrunner** [comment]
Ist mit Modulversion 2.2.0 jetzt wieder `Überlebenskunst` und `Naturkunde` :) Nochmal danke für die Meldung!
